### ISSUE TITLE
Compatibility issue with tablewriter v1.0

### ISSUE THREAD

**Issue by hibare** [nao1215/markdown#49]
## Describe the bug
tablewriter has transitioned to major version v1.0 and is not fully backword compatible.

Related issue on tablewriter: https://github.com/olekukonko/tablewriter/issues/270

## Steps to reproduce
Use example from README.md and ensure github.com/olekukonko/tablewriter v1.0.6 is installed

## Expected behavior
Markdown library works without any errors

## Additional context
Few logs:
```
/Users/john/go/1.24.2/pkg/mod/github.com/nao1215/markdown@v0.7.1/markdown.go:350:8: table.SetBorders undefined (type *tablewriter.Table has no field or method SetBorders)
/Users/john/go/1.24.2/pkg/mod/github.com/nao1215/markdown@v0.7.1/markdown.go:350:31: undefined: tablewriter.Border
/Users/john/go/1.24.2/pkg/mod/github.com/nao1215/markdown@v0.7.1/markdown.go:351:8: table.SetCenterSeparator undefined (type *tablewriter.Table has no field or method SetCenterSeparator)
/Users/john/go/1.24.2/pkg/mod/github.com/nao1215/markdown@v0.7.1/markdown.go:352:8: table.SetHeader undefined (type *tablewriter.Table has no field or method SetHeader)
/Users/john/go/1.24.2/pkg/mod/github.com/nao1215/markdown@v0.7.1/markdown.go:383:8: table.SetNewLine undefined (type *tablewriter.Table has no field or method SetNewLine)
/Users/john/go/1.24.2/pkg/mod/github.com/nao1215/markdown@v0.7.1/markdown.go:384:8: table.SetBorders undefined (type *tablewriter.Table has no field or method SetBorders)
/Users/john/go/1.24.2/pkg/mod/github.com/nao1215/markdown@v0.7.1/markdown.go:384:31: undefined: tablewriter.Border
/Users/john/go/1.24.2/pkg/mod/github.com/nao1215/markdown@v0.7.1/markdown.go:385:8: table.SetCenterSeparator undefined (type *tablewriter.Table has no field or method SetCenterSeparator)
/Users/john/go/1.24.2/pkg/mod/github.com/nao1215/markdown@v0.7.1/markdown.go:386:8: table.SetAutoWrapText undefined (type *tablewriter.Table has no field or method SetAutoWrapText)
/Users/john/go/1.24.2/pkg/mod/github.com/nao1215/markdown@v0.7.1/markdown.go:386:8: too many errors
```

**Comment by olekukonko** [comment]
This was designed to work with version v0.0.5, I believe. See: https://github.com/nao1215/markdown/blob/6abde2b9f9db70018fd05429ad86fe61cc78c592/go.mod#L10

**Comment by nao1215** [comment]
@hibare 
Thank you for the report.
I fix it. See https://github.com/nao1215/markdown/pull/52
